### ISSUE TITLE
Unable to join with Zoom link

### ISSUE THREAD

**Issue by tram-nguyen-n** [waldronlab/data-science-seminar#14]
Hi all,

Is the Zoom link still the same as the one posted in the Google Groups for the Advanced R club? I haven't been able to join the meeting using that link for the last two meetings. Please let me know if I should try with something else.

Thanks!
Tram

**Comment by LiNk-NY** [comment]
Hi @tram-nguyen-n 
Sorry for the inconvenience. We haven't had meetings for the last two weeks. 
We will do better to update the schedule before the meetings. 
cc: @cmirzayi

**Comment by tram-nguyen-n** [comment]
Ah ok, thanks for the update @LiNk-NY!
Just wanted to check since I signed up to present this coming Friday, but it sounds like we are still on Chapter 12. So I'll hold off on prepping. Thanks again!

**Comment by cmirzayi** [comment]
Hi Tram,

So sorry about the confusion. This is totally my bad. As Marcel said, we skipped two weeks due to 1) me getting a sinus infection and 2) a scheduling conflict at the Waldron Lab.

We will resume this week with my presentation on chapter 12.

Thank you so much for participating and for checking in!
